# docker compose down -v
# docker-compose up -d
services:
  backend:
    image: dockerracdockerrac/shipper-station
    restart: always
    ports:
      - 8080:8080
    environment:
       ConnectionStrings__DefaultConnection: server=db;user=root;password=12345;database=ShipperStation
       ConnectionStrings__Redis: redis:6379

  db:
    image: mysql:8.2.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    ports:
      - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: 12345
        MYSQL_DATABASE: ShipperStation

  redis:
    image: redis
    ports:
      - 6000:6379

volumes:
  mysql_data:
  mysql_config: