//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipperStation.Application.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShipperStation.Application.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request. Please provide valid data..
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity already exists!.
        /// </summary>
        public static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device created successfully.
        /// </summary>
        public static string DeviceCreatedSuccess {
            get {
                return ResourceManager.GetString("DeviceCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device deleted successfully.
        /// </summary>
        public static string DeviceDeletedSuccess {
            get {
                return ResourceManager.GetString("DeviceDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device token already registered.
        /// </summary>
        public static string DeviceTokenAlreadyRegistered {
            get {
                return ResourceManager.GetString("DeviceTokenAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Token is conflict.
        /// </summary>
        public static string DeviceTokenConflict {
            get {
                return ResourceManager.GetString("DeviceTokenConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device token registered successfully.
        /// </summary>
        public static string DeviceTokenRegisteredSuccess {
            get {
                return ResourceManager.GetString("DeviceTokenRegisteredSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device updated successfully.
        /// </summary>
        public static string DeviceUpdatedSuccess {
            get {
                return ResourceManager.GetString("DeviceUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} ({1}) already exists!.
        /// </summary>
        public static string EntityConflict {
            get {
                return ResourceManager.GetString("EntityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity {0} ({1}) was not found..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file failed.
        /// </summary>
        public static string FileDeleteFailed {
            get {
                return ResourceManager.GetString("FileDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file failed.
        /// </summary>
        public static string FileUploadFailed {
            get {
                return ResourceManager.GetString("FileUploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied. You are not authorized to perform this action..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong on the server. Please contact the administrator..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token is not valid..
        /// </summary>
        public static string InvalidRefreshToken {
            get {
                return ResourceManager.GetString("InvalidRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find what you were looking for..
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực của bạn là {0}.
        /// </summary>
        public static string NotificationContentOtpMessage {
            get {
                return ResourceManager.GetString("NotificationContentOtpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification deleted successfully.
        /// </summary>
        public static string NotificationDeletedSuccess {
            get {
                return ResourceManager.GetString("NotificationDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification type {0} is not supported.
        /// </summary>
        public static string NotificationNotSupported {
            get {
                return ResourceManager.GetString("NotificationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification status updated success.
        /// </summary>
        public static string NotificationStatusUpdatedSuccess {
            get {
                return ResourceManager.GetString("NotificationStatusUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string NotificationTitleOtpMessages {
            get {
                return ResourceManager.GetString("NotificationTitleOtpMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is invalid.
        /// </summary>
        public static string OtpInvalid {
            get {
                return ResourceManager.GetString("OtpInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otp is null.
        /// </summary>
        public static string OtpIsNull {
            get {
                return ResourceManager.GetString("OtpIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is required.
        /// </summary>
        public static string OtpRequired {
            get {
                return ResourceManager.GetString("OtpRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Otp successfully.
        /// </summary>
        public static string OtpSendSuccess {
            get {
                return ResourceManager.GetString("OtpSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string PasswordSetSuccess {
            get {
                return ResourceManager.GetString("PasswordSetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number existed.
        /// </summary>
        public static string PhoneNumberExisted {
            get {
                return ResourceManager.GetString("PhoneNumberExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is invalid.
        /// </summary>
        public static string PhoneNumberInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefreshToken is required.
        /// </summary>
        public static string RefreshTokenRequired {
            get {
                return ResourceManager.GetString("RefreshTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff created successfully.
        /// </summary>
        public static string StaffCreatedSuccess {
            get {
                return ResourceManager.GetString("StaffCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff is not found.
        /// </summary>
        public static string StaffNotFound {
            get {
                return ResourceManager.GetString("StaffNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store manager created successfully.
        /// </summary>
        public static string StoreManagerCreatedSuccess {
            get {
                return ResourceManager.GetString("StoreManagerCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication required. Please provide valid credentials..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You account is haved password.
        /// </summary>
        public static string UserHavePassword {
            get {
                return ResourceManager.GetString("UserHavePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Is Inactive.
        /// </summary>
        public static string UserIsInactive {
            get {
                return ResourceManager.GetString("UserIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username existed.
        /// </summary>
        public static string UsernameExisted {
            get {
                return ResourceManager.GetString("UsernameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ({0}) not have device ({1}).
        /// </summary>
        public static string UserNotHaveDevice {
            get {
                return ResourceManager.GetString("UserNotHaveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ({0}) not have notification ({1}).
        /// </summary>
        public static string UserNotHaveNotification {
            get {
                return ResourceManager.GetString("UserNotHaveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not the manager of this station.
        /// </summary>
        public static string UserNotInStation {
            get {
                return ResourceManager.GetString("UserNotInStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully.
        /// </summary>
        public static string UserUpdatedProfileSuccess {
            get {
                return ResourceManager.GetString("UserUpdatedProfileSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple errors occurred. See error details..
        /// </summary>
        public static string ValidationBadRequest {
            get {
                return ResourceManager.GetString("ValidationBadRequest", resourceCulture);
            }
        }
    }
}
